version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - npm run lint

  build:
    commands:
      - echo "Running build..."
      - npm run build
      - echo "Build completed"

  post_build:
    commands:
      - echo "Post-build actions..."
      - npm test
      # Example: Upload build artifacts to S3
      # aws s3 cp ./dist s3://your-bucket-name/ --recursive

artifacts:
  files:
    - '/*'
  discard-paths: yes
  base-directory: dist
